app:
  image: vimagick/pptpd
  environment:
   - VIRTUAL_HOST=vpn.misterbanal.net
  ports:
   - 1723:1723
  volumes:
   - ./pptpd.conf:/etc/pptpd.conf
   - ./pptpd-options:/etc/ppp/pptpd-options
   - ./chap-secrets:/etc/ppp/chap-secrets
  privileged: true
  net: "host"
